create table if not exists public.expense_requests (
  id bigint generated by default as identity primary key,
  request_date date not null,
  account text not null,
  expense_type text not null,
  category text not null,
  vendor text,
  amount numeric not null default 0,
  content text not null,
  payment_method text,
  receipt_url text not null default '',
  memo text,
  status text not null default '승인대기',
  requested_by text not null,
  requested_name text,
  approved_by text,
  approved_name text,
  approved_at timestamptz,
  reject_reason text,
  created_at timestamptz not null default now()
);

create index if not exists expense_requests_status_idx
on public.expense_requests (status);

create index if not exists expense_requests_requested_by_idx
on public.expense_requests (requested_by);

create index if not exists expense_requests_request_date_idx
on public.expense_requests (request_date);

insert into storage.buckets (id, name, public)
values ('expense-receipts', 'expense-receipts', true)
on conflict (id) do update set public = true;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'expense receipts read'
  ) then
    create policy "expense receipts read"
    on storage.objects
    for select
    to anon
    using (bucket_id = 'expense-receipts');
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'expense receipts upload'
  ) then
    create policy "expense receipts upload"
    on storage.objects
    for insert
    to anon
    with check (bucket_id = 'expense-receipts');
  end if;
end $$;
