create table if not exists public.attendance_requests (
  id bigint generated by default as identity primary key,
  request_type text not null,
  start_date date not null,
  end_date date,
  start_time time,
  end_time time,
  reason text not null,
  memo text,
  status text not null default '부서장 승인대기',
  requested_by text not null,
  requested_name text,
  requested_department text,
  department_approved_by text,
  department_approved_name text,
  department_approved_at timestamptz,
  admin_dept_approved_by text,
  admin_dept_approved_name text,
  admin_dept_approved_at timestamptz,
  final_approved_by text,
  final_approved_name text,
  final_approved_at timestamptz,
  approved_by text,
  approved_name text,
  approved_at timestamptz,
  reject_reason text,
  created_at timestamptz not null default now()
);

alter table public.attendance_requests
add column if not exists requested_department text,
add column if not exists department_approved_by text,
add column if not exists department_approved_name text,
add column if not exists department_approved_at timestamptz,
add column if not exists admin_dept_approved_by text,
add column if not exists admin_dept_approved_name text,
add column if not exists admin_dept_approved_at timestamptz,
add column if not exists final_approved_by text,
add column if not exists final_approved_name text,
add column if not exists final_approved_at timestamptz;

alter table public.attendance_requests
alter column status set default '부서장 승인대기';

create index if not exists attendance_requests_status_idx
on public.attendance_requests (status);

create index if not exists attendance_requests_requested_by_idx
on public.attendance_requests (requested_by);

create index if not exists attendance_requests_start_date_idx
on public.attendance_requests (start_date);
